import 'dolphin.dart';
import 'bat.dart';
import 'cat.dart';
import 'dove.dart';
import 'duck.dart';
import 'shark.dart';
import 'flying_fish.dart';

void main(List<String> args) {
  Dolphin lumbaLumba = Dolphin("Dolphin", 2, "Biru");
  lumbaLumba.greeting();
  lumbaLumba.animalType();
  lumbaLumba.showInfo();
  lumbaLumba.swim();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  Bat kelelawar = Bat("Bat", 2, "Biru");
  kelelawar.greeting();
  kelelawar.animalType();
  kelelawar.showInfo();
  kelelawar.walk();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  Cat kucing = Cat("Cat", 2, "Biru");
  kucing.greeting();
  kucing.animalType();
  kucing.showInfo();
  kucing.walk();
  kucing.fly();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  Dove merpati = Dove("Dove", 2, "Biru");
  merpati.greeting();
  merpati.animalType();
  merpati.showInfo();
  merpati.walk();
  merpati.fly();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  Duck bebek = Duck("Duck", 2, "Biru");
  bebek.greeting();
  bebek.animalType();
  bebek.showInfo();
  bebek.walk();
  bebek.swim();
  bebek.fly();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  Shark hiu = Shark("Shark", 2, "Biru");
  hiu.greeting();
  hiu.animalType();
  hiu.showInfo();
  hiu.swim();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
  FlyingFish burungTerbang = FlyingFish("FlyingFish", 2, "Biru");
  burungTerbang.greeting();
  burungTerbang.animalType();
  burungTerbang.showInfo();
  burungTerbang.swim();
  burungTerbang.fly();
  print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
}